---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: El nombre que acabás de ingresar
  checked: true
- value: "`git name set`"
  checked: false
- value: "`unknown option`"
  checked: false
