---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: Hi! I am git <VERSION>
  checked: false
- value: git version is <VERSION>
  checked: false
- value: git version <VERSION>
  checked: true
